---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 764440121517170688-dw1mTGgJbuKrCE2N0av8OOiDU5Wg6SL
:access_token_secret: MnGOm3qq6ABJC8mvWYgOOobdH5s7fEBo2ox0k7WWopAaz
